### ISSUE TITLE
jsonb_to_zson ignores repalloc return value

### ISSUE THREAD

**Issue by tvondra** [postgrespro/zson#21]
I guess this should be

`encoded_buff = repalloc(encoded_buff, encoded_size);`

https://github.com/postgrespro/zson/blob/a7256fadc04d8033acd6cf72206dbff814fdd164/zson.c#L533

**Comment by afiskon** [comment]
@tvondra thanks, Tomas. Fixed in https://github.com/postgrespro/zson/commit/02db084ea3b94d9e68fd912dea97094634fcdea5
