### ISSUE TITLE
JSON schema validation

### ISSUE THREAD

**Issue by dlight** [postgrespro/zson#23]
Does zson work with any json schema validation extension, like [is_jsonb_valid](https://github.com/furstenheim/is_jsonb_valid) or [postgres_json_schema](https://github.com/gavinwahl/postgres-json-schema) or some other extension? (preferably the former)

Is this only possible by converting to jsonb? If yes, does it makes sense for this extension to also provide a validation function?

**Comment by afiskon** [comment]
ZSON is going to work with any extension that provides extra functionality for JSONB. I don't see how implementing schema validation in ZSON is going to be beneficial.
