### ISSUE TITLE
Usage example doesn't work

### ISSUE THREAD

**Issue by namoshizun** [postgrespro/zson#24]
Hiiii, I installed this extension on pg15 and tried the usage example given in the README. I encountered the following error.... not sure if I missed something important or it is that ZSON doesn't work on 15.

```
tsitamani=# create table zson_example(x zson);
CREATE TABLE

tsitamani=# select * from zson_example ;
 x
---
(0 rows)


tsitamani=# insert into zson_example values ('{"aaa": 123}');
ERROR:  Unable to compress jsonb
LINE 1: insert into zson_example values ('{"aaa": 123}');
                                         ^
DETAIL:  zson_dict is not initialized
HINT:  You probably forgot to execute zson_learn(). In case you are restoring from a backup made via pg_dump, just move the content of zson_dict table above the current line.
```

Seeing the HINT, I then execute zson_learn, but that doesn't help either, which make sense because the example table is still empty.

```
tsitamani=# select zson_learn('{{"zson_example", "x"}}');
                                  zson_learn
-------------------------------------------------------------------------------
 Done! Run " select * from zson_dict where dict_id = 0; " to see a dictionary.
(1 row)


tsitamani=# insert into zson_example values ('{"aaa": 123}');
ERROR:  Unable to compress jsonb
LINE 1: insert into zson_example values ('{"aaa": 123}');
                                         ^
DETAIL:  zson_dict is not initialized
HINT:  You probably forgot to execute zson_learn(). In case you are restoring from a backup made via pg_dump, just move the content of zson_dict table above the current line.
```

**Comment by namoshizun** [comment]
BTW, this is the table inspection output

```
tsitamani=# \d+ zson_example
                                     Table "public.zson_example"
 Column | Type | Collation | Nullable | Default | Storage  | Compression | Stats target | Description
--------+------+-----------+----------+---------+----------+-------------+--------------+-------------
 x      | zson |           |          |         | extended |             |              |
Access method: heap
```

**Comment by afiskon** [comment]
You have to initialize the dictionary with zson_learn() on the actual documents before using ZSON type:

```
DETAIL:  zson_dict is not initialized
```

zson_learn() does nothing in your case because the table is empty. Alternatively you can fill zson_dict table manually.

**Comment by afiskon** [comment]
@namoshizun well, on second thought you shouldn't do this except for maybe test purposes.

What I would recommend to do rather is something like:

```
=# create table jsonb_example(x jsonb);
CREATE TABLE

=# -- your common documents: more is better!
=# insert into jsonb_example values ('{"hello":"world"}');
INSERT 0 1

=# create table my_common_data(id SERIAL PRIMARY KEY, x jsonb);
CREATE TABLE

=# -- sample data
=# insert into my_common_data select * from generate_series(1, 10000), jsonb_example;
INSERT 0 10000

=# select zson_learn('{{"my_common_dta", "x"}}');
                                  zson_learn
-------------------------------------------------------------------------------
 Done! Run " select * from zson_dict where dict_id = 0; " to see a dictionary.

1033525 (master) =# select * from zson_dict;
 dict_id | word_id | word
---------+---------+-------
       0 |       1 | hello
       0 |       2 | world
```

BTW I just tested the extension on the current `master` branch of PostgreSQL - it still works.

**Comment by namoshizun** [comment]
@afiskon Thanks for the clarification! The example you give shows that `zson_learn` can learn the dict for compression on `jsonb` data. But I am still confused why the original usage example (as given in the README) doesn't work, where the example table created defines `zson` column...

**Comment by namoshizun** [comment]
Ohhhh I think I realise what was odd. So in my first attempt, I ran the Usage example on an initially empty pgsql instance (I used Docker). At that point, both the `zson_example` and `zson_dict` are blank.

It appears that when the `zson_dict` has absolutely nothing, inserting data into an initially empty table with `zson` column would fail. After creating another table using `jsonb` and populate `zson_dict` the same way you suggested, I was able to then run the Usage example without error.

**Comment by afiskon** [comment]
👍

**Comment by namoshizun** [comment]
> Ohhhh I think I realise what was odd. So in my first attempt, I ran the Usage example on an initially empty pgsql instance (I used Docker). At that point, both the `zson_example` and `zson_dict` are blank.
> 
> It appears that when the `zson_dict` has absolutely nothing, inserting data into an initially empty table with `zson` column would fail. After creating another table using `jsonb` and populate `zson_dict` the same way you suggested, I was able to then run the Usage example without error.

@afiskon  Uhhh so is it a bug? It seems odd that `zson_dict` table must be somehow populated before a zson table can ben inserted, but the `zson_dict` can't be initialized until the zson table has something in it...

**Comment by afiskon** [comment]
@namoshizun  zson_learn() should be learned on documents of JSONB type, not ZSON. Please read both README and the example provided above very carefully. The extension works as intended.

Perhaps the wording in README could be better though. Feel free submitting a corresponding patch.
