### ISSUE TITLE
Is this usable in production?

### ISSUE THREAD

**Issue by dclipca** [postgrespro/zson#27]
Hello @afiskon, can I use this in production? Not sure if absence of recent commits means the extension is stable or abandoned. This is you in https://www.postgresql.org/message-id/CAJ7c6TN11%3DH-L1jT8YC8zpmEW0UVuh9D6xp47ajgcWWv%2Bq16GQ%40mail.gmail.com right? Was the JSONB compression patch accepted/integrated? Also, I wonder whatever ZSON or this JSONB patch in the Postgres correspondence emails employs ZSTD compression via repeated words (dictionary-based). What is your recommendation for efficiently compressing JSONB in Postgres nowadays?

**Comment by afiskon** [comment]
Yes, that's me. To my knowledge ZSON is pretty stable. The "compression dictionaries" feature for PG core is still in development https://commitfest.postgresql.org/46/3626/ Please consider joining the effort as an reviewer, tester or a co-author. The patch needs more attention from the community.

**Comment by dclipca** [comment]
I made an account and will try to review once the cool-off period is off.
