### ISSUE TITLE
create extension zson; fails. missing extension/zson--1.1.sql

### ISSUE THREAD

**Issue by handerpeder** [postgrespro/zson#7]
Seems you've forgotten to add an updated extension file.

To reproduce on b3a7091
```
$ make && sudo make install
$ psql -c 'create extension zson'
ERROR:  could not stat file "/usr/share/postgresql/extension/zson--1.1.sql": No such file or directory
```

**Comment by afiskon** [comment]
Interesting. I've tested zson 1.1 on PostgreSQL 10 where create extension just worked. I'll fix this but I have to know what version of PostgreSQL you are using to reproduce it.

**Comment by afiskon** [comment]
https://github.com/postgrespro/zson/commit/e176165bcff308dbeb02f16278f3b56f3f6e02d8 should fix this. Please check.

**Comment by afiskon** [comment]
OK, I've just checked it on Ubuntu 16.04 and PostgreSQL 9.4.12. The problem seems to be fixed.
