### ISSUE TITLE
Create Git tags and GitHub releases

### ISSUE THREAD

**Issue by rleonhardt** [postgrespro/zson#8]
Please create create Git tags and [GitHub releases](https://help.github.com/articles/creating-releases/) to allow subscribers of services like sibbell.com to be automatically notified.

Thank you very much for this great extension, transparent JSONB compression should have been built-in from the beginning, another milestone to make Postgres the most powerful and fastest NoSQL datastore for many use cases, kudos!

**Comment by afiskon** [comment]
Sounds like something worth doing. Fixed, thanks!
