### ISSUE TITLE
Suggest bundling as BigSQL component

### ISSUE THREAD

**Issue by rleonhardt** [postgrespro/zson#9]
Suggest bundling ZSON as a [BigSQL component](https://www.bigsql.org/components/) to allow installing and updating the extension conveniently for Linux, macOS and Windows.

**Comment by afiskon** [comment]
Hi.

I don't know much about BigSQL. If it's "100% Pure Core PostgreSQL" as title claims ZSON should work with it already. In case you have problems with ZSON on any mentioned platform, please be more specific.
